baseURL = "https://blog.on-going.jp/"
languageCode = "jp"
title = "on-going's Blog"
hasCJKLanguage = true

# Copyright notice. This is displayer in the footer.
copyright = "<em>&copy; 2020 on-going.</em>"
custom_css = "/static/css/custom.css"

# Google Analytics API key.
googleAnalytics = "UA-166112919-2"



[params]
  # Disqus shortname
  author = "相馬 大知 (Taichi Soma)"
  authorwebsite = "www.on-going.jp"
  avatar = "/images/profile.jpg"
  bio = "ダイガクインセイ"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "無名天地之始、有名万物之母"
  # Logo image. This is displayed ogp image.
  logo = "/images/profile.jpg"
  commpost = true



[[menu.main]]
    name = "Home"
    url = "http://on-going.jp"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "http://blog.on-going.jp"
    weight = 2

[[menu.main]]
    name = "Tech Blog"
    url = "http://techblog.on-going.jp"
    weight = 3

[[menu.main]]
    name = "Portfolio"
    url = "http://on-going.jp/portfolio/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "http://on-going.jp/about/"
    weight = 5
